### PR TITLE
SPA cancer types summary - make controls more compact

### PR DESCRIPTION
**Pull request by adamabeshouse**
https://github.com/cBioPortal/cbioportal/issues/4823

### CODE REVIEW

**Comment by alisman** [comment]
@adamabeshouse lets get feedback from JJ before we merge this.  can you put a screenshot or make heroku?

**Comment by adamabeshouse** [comment]
image

**Comment by alisman** [comment]
@jj can you you comment on this layout (see screenshot)

**Comment by jjgao** [comment]
Thanks. This is definitely better than what we have. I am wondering if we can/should make it more compact, but let's go with this for now.

**Pull request closed without merging**
